# Generated by Django 5.2.12 on 2026-05-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlacklistedToken",
        ),
        migrations.DeleteModel(
            name="OutstandingToken",
        ),
    ]
